spring:
  profiles:
    active: test



---
#Postgres
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: root
  jpa:
    hibernate:
      ddl-auto: create

---
#H2
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    password: sa
    username:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
#
#logging:
#  level:
#    root: DEBUG

---
# MysqlDB

spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://192.168.1.41:3310/operator?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    password: test
    username: test


